AddCSLuaFile()
SWEP.Spawnable = true
SWEP.Category = "Arctic VR"
SWEP.AdminOnly = false
SWEP.UseHands = false
SWEP.Base = "arcticvr_base"
SWEP.ViewModel = "models/weapons/arcticvr/rifle_famas.mdl"
SWEP.WorldModel = "models/weapons/w_rif_famas.mdl"
SWEP.ArcticVR = true
SWEP.Primary.ClipSize = 25
SWEP.Primary.DefaultClip = 1000
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "smg1"
SWEP.Secondary.ClipSize = -1
SWEP.Secondary.DefaultClip = -1
SWEP.Secondary.Automatic = false
SWEP.Secondary.Ammo = "none"
SWEP.Weight = 5
SWEP.AutoSwitchTo = false
SWEP.AutoSwitchFrom = false
SWEP.PrintName = "VR FAMAS"
SWEP.Slot = 3
SWEP.SlotPos = 3
SWEP.DrawAmmo = false
SWEP.DrawCrosshair = false
SWEP.DamageMin = 24
SWEP.DamageMax = 45
SWEP.MaxRange = 9000
SWEP.Penetration = 15
SWEP.MuzzleVelocity = 16500
SWEP.TracerCol = Color(255, 200, 0)
SWEP.TracerWidth = 3
SWEP.RPM = 900
SWEP.Firemode = -3
SWEP.Recoil = 1.25
SWEP.RecoilVertical = 3.5
SWEP.RecoilSide = 1.75
SWEP.RecoilBalance = Vector(-1, 0, 0.75)
SWEP.Spread = 1 / 150
SWEP.MeanShotsBetweenJams = 0
SWEP.AmmoType = "smg1"
SWEP.MagType = "famas"
SWEP.DefaultMagazine = "famas_25"
SWEP.MuzzleEffect = "CS_MuzzleFlash"
SWEP.CaseEffect = "arcticvr_case_556"
SWEP.BulletEffect = "arcticvr_bullet_556"
SWEP.FireSound = "weapons/famas/famas-1.wav"
SWEP.DryFireSound = "weapons/clipempty_pistol.wav"
SWEP.SwitchModeSound = "weapons/ar2/ar2_empty.wav"
SWEP.SlideBackSound = "weapons/arcticvr/famas_boltback.wav"
SWEP.SlideForwardSound = "weapons/arcticvr/famas_boltforward.wav"
SWEP.MagInSound = "weapons/famas/famas_clipin.wav"
SWEP.MagOutSound = "weapons/famas/famas_clipout.wav"
SWEP.SpawnMagSound = "foley/eli_hand_pat.wav"
if CLIENT then
    g_VR.viewModelInfo = g_VR.viewModelInfo or {}
    g_VR.viewModelInfo.arcticvr_famas = {
        offsetPos = Vector(5.5, 1.25, 2.5), --forward, left, up
        offsetAng = Angle(0, 0, 0),
    }

    SWEP.NonReciprocatingChargingHandle = false
    SWEP.CanLockBack = false
    SWEP.MagCanDropFree = false
    SWEP.BoltCanAutoRelease = false
    SWEP.CHandleRaise = false
    SWEP.HKSlap = false
    SWEP.TwoHanded = true
    SWEP.RTScope = true -- weapon has an RT scope
    SWEP.RTScopeSubmatIndex = 1 -- what is the submaterial index of the scope material?
    SWEP.RTScopeFOV = 15 / 3 -- what is the field of view of the scope?
    SWEP.RTScopeRes = 256
    SWEP.RTScopeSurface = Material("effects/avr_rt")
    SWEP.RTScopeOffset = Vector(0, 0, 0)
    SWEP.RTScopeReticle = Material("scopes/acog.png")
    SWEP.StabilityFrames = 5
    SWEP.ForegripAngle = Angle(0, -90, -90)
    SWEP.ForegripOffset = Vector(12, -4, 3)
    SWEP.ForegripMins = Vector(-4, -4, -5)
    SWEP.ForegripMaxs = Vector(4, 1, 5)
    SWEP.SlideMins = Vector(-3, -3, -3)
    SWEP.SlideMaxs = Vector(3, 3, 3)
    SWEP.MagazineInsertMins = Vector(-3, -4, -3)
    SWEP.MagazineInsertMaxs = Vector(3, 0, 3)
    SWEP.MagazineOffset = Vector(0, 0, 0)
    SWEP.MagazineAngleOffset = Angle(0, 0, 0)
    SWEP.SlideDir = Vector(0, 0, -1)
    SWEP.SlideBlowbackAmount = 4.14501
    SWEP.BoneIndices = {
        famas = 0,
        mag = 1,
        trigger = 2,
        slide = 3,
        muzzle = 4,
        eject = 5,
        foregrip = 6,
        scope = 7,
    }

    SWEP.FireSelectPoses = {
        [0] = {},
        [1] = {},
        [-3] = {},
    }

    SWEP.Firemodes = {-3, 1, 0}
end